In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data = pd.read_excel('Ruta_Vendedor.xlsx')
data.head()

,Fecha,Codigo_Vendedor,Nombre_Vendedor,Codigo_FV,FV,Codigo_Proveedor,Nombre_Proveedor,Codigo_Cliente,Nombre_Cliente,Marca,...,Total,Distrito,Categoria_Cliente,Tipo_Cliente,TipoDocIdentidad,DocIdentidad,NumeroTelefono,VendedorZonaCodigo,LATITUD,LONGITUD
0,2021-01-04,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20264846855,CLOROX PERU S.A. ...,119719,"HUERTA ROQUE, NOELIA ADILA ...",CLOROX,...,17.2710,PUENTE PIEDRA,COBERTURA,BODEGA BASICA,Libreta Electoral DNI,10396625,928419117 (OK),0107MIB,-11.876642,-77.07192
1,2021-01-04,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20524152763,SUPERFORTE PERU S.A.C ...,119719,"HUERTA ROQUE, NOELIA ADILA ...",FORTE,...,4.0400,PUENTE PIEDRA,COBERTURA,BODEGA BASICA,Libreta Electoral DNI,10396625,928419117 (OK),0107MIB,-11.876642,-77.07192
2,2021-01-04,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20524152763,SUPERFORTE PERU S.A.C ...,119719,"HUERTA ROQUE, NOELIA ADILA ...",FORTE,...,4.0400,PUENTE PIEDRA,COBERTURA,BODEGA BASICA,Libreta Electoral DNI,10396625,928419117 (OK),0107MIB,-11.876642,-77.07192
3,2021-01-04,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20524152763,SUPERFORTE PERU S.A.C ...,119719,"HUERTA ROQUE, NOELIA ADILA ...",FORTE,...,4.0400,PUENTE PIEDRA,COBERTURA,BODEGA BASICA,Libreta Electoral DNI,10396625,928419117 (OK),0107MIB,-11.876642,-77.07192
4,2021-01-04,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20204441007,JOHNSON Y JOHNSON DEL PERU S.A. ...,119719,"HUERTA ROQUE, NOELIA ADILA ...",JOHNSON & JOHNSON,...,13.2824,PUENTE PIEDRA,COBERTURA,BODEGA BASICA,Libreta Electoral DNI,10396625,928419117 (OK),0107MIB,-11.876642,-77.07192

In [3]:
data['Fecha'] = pd.to_datetime(data['Fecha'])
data['Dia_Semana'] = data['Fecha'].dt.day_name()

data['Rechazo'] = data['Total'] < 0

#Mostrar las siguientes columnas
data[['Fecha', 'Dia_Semana', 'Codigo_Cliente', 'Nombre_Cliente', 'Total', 'Rechazo']].head()

,Fecha,Dia_Semana,Codigo_Cliente,Nombre_Cliente,Total,Rechazo
0,2021-01-04,Monday,119719,"HUERTA ROQUE, NOELIA ADILA ...",17.2710,False
1,2021-01-04,Monday,119719,"HUERTA ROQUE, NOELIA ADILA ...",4.0400,False
2,2021-01-04,Monday,119719,"HUERTA ROQUE, NOELIA ADILA ...",4.0400,False
3,2021-01-04,Monday,119719,"HUERTA ROQUE, NOELIA ADILA ...",4.0400,False
4,2021-01-04,Monday,119719,"HUERTA ROQUE, NOELIA ADILA ...",13.2824,False

In [4]:
data['Total_Compra'] = data.groupby(['Codigo_Cliente', 'Fecha'])['Total'].transform('sum')

In [5]:
columnas_a_eliminar = ['Codigo_FV', 'FV', 'Codigo_Proveedor', 'Nombre_Proveedor', 'Marca', 'Linea', 'Codigo_Producto', 'Nombre_Producto',
                       'Cantidad', 'Factor', 'ValorVenta', 'Total', 'Categoria_Cliente', 'Tipo_Cliente', 'TipoDocIdentidad', 'DocIdentidad',
                       'NumeroTelefono', 'VendedorZonaCodigo']

data = data.drop(columns=columnas_a_eliminar)

In [6]:
data = data.drop_duplicates(subset=['Codigo_Cliente', 'Fecha'])

# ConstrucciÃ³n del modelo

In [7]:
data_enconded = pd.get_dummies(data[['Dia_Semana']], drop_first=True)

data_enconded['Rechazo'] = data['Rechazo']

X = data_enconded.drop('Rechazo', axis=1)
y = data_enconded['Rechazo']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


print("Classification Report:")
print(classification_report(y_test, y_pred))

print("confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00      7882
        True       0.00      0.00      0.00         7

    accuracy                           1.00      7889
   macro avg       0.50      0.50      0.50      7889
weighted avg       1.00      1.00      1.00      7889

confusion Matrix
[[7882    0]
 [   7    0]]

C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [8]:
# Crear un dataframe con los clientes Ãºnicos y sus dÃ­as sin rechazos
data_no_rechazos = data[data['Rechazo'] == False]

# Agrupar por cliente y dÃ­a de la semana para encontrar los dÃ­as sin rechazos
clientes_dias_no_rechazo = data_no_rechazos.groupby(['Codigo_Cliente', 'Nombre_Cliente'])['Dia_Semana'].apply(lambda x: list(x.unique())).reset_index()

# Renombrar las columnas
clientes_dias_no_rechazo.columns = ['Codigo_Cliente', 'Nombre_Cliente', 'Dias_Sin_Rechazo']

# Mostrar el dataframe resultante
clientes_dias_no_rechazo.head()

,Codigo_Cliente,Nombre_Cliente,Dias_Sin_Rechazo
0,219,"RAMOS ROJAS, JUANY CONZUELO ...","[Thursday, Monday]"
1,220,CHAVEZ PECHE BAUTISTA EUSEVIO ...,"[Thursday, Monday, Sunday]"
2,222,BENDEZU CHAVEZ JUSTINA WILFRIDA/FARMACIA SAN F...,"[Wednesday, Monday, Thursday]"
3,223,URIOL VALVERDE PABLO HIPOLITO ...,"[Monday, Thursday, Sunday, Wednesday]"
4,386,CAMPOS CASTAÃ‘EDA SONIA LUISA ...,"[Monday, Thursday]"

In [9]:
clientes_dias_no_rechazo.to_excel('clientes_dias_sin_rechazo.xlsx', index=False)

In [10]:
import pandas as pd

# Supongamos que 'data' es el dataframe original que cargamos al principio
# Y 'clientes_dias_no_rechazo' es el dataframe procesado

# Unir el dataframe original con el dataframe de dÃ­as sin rechazo
data_completo = data.merge(clientes_dias_no_rechazo, on=['Codigo_Cliente', 'Nombre_Cliente'], how='left')

# Guardar el dataframe completo a un archivo Excel
output_path_completo = 'clientes_dias_sin_rechazo_completo.xlsx'
data_completo.to_excel(output_path_completo, index=False)

print(f"Archivo exportado a {output_path_completo}")

Archivo exportado a clientes_dias_sin_rechazo_completo.xlsx