In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data = pd.read_excel('prueba.xlsx')
data.head()

,Fecha,Codigo_Vendedor,Nombre_Vendedor,Codigo_FV,FV,Codigo_Proveedor,Nombre_Proveedor,Codigo_Cliente,Nombre_Cliente,Marca,...,Total,Distrito,Categoria_Cliente,Tipo_Cliente,TipoDocIdentidad,DocIdentidad,NumeroTelefono,VendedorZonaCodigo,LATITUD,LONGITUD
0,2023-01-03,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20604027862,LAKASA PERU S.A. ...,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",MAGIA,...,6.6825,LOS OLIVOS,COBERTURA,BODEGA TIPICA,Libreta Electoral DNI,40868050,971815115,0107JUBC,-11.995142,-77.070522
1,2023-01-03,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20604027862,LAKASA PERU S.A. ...,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",MAGIA,...,7.1508,LOS OLIVOS,COBERTURA,BODEGA TIPICA,Libreta Electoral DNI,40868050,971815115,0107JUBC,-11.995142,-77.070522
2,2023-01-03,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20521948061,COSTA VIVA S.A.C. ...,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",TIMONEL,...,6.2800,LOS OLIVOS,COBERTURA,BODEGA TIPICA,Libreta Electoral DNI,40868050,971815115,0107JUBC,-11.995142,-77.070522
3,2023-01-03,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20100170842,PRODUCTOS EXTRAGEL Y UNIVERSAL S.A.C. ...,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",UNIVERSAL,...,9.6600,LOS OLIVOS,COBERTURA,BODEGA TIPICA,Libreta Electoral DNI,40868050,971815115,0107JUBC,-11.995142,-77.070522
4,2023-01-03,01C07,"C07 ALVAREZ OSCCO, DALMACIO PERCY ...",107,RUTA Mixta C,20100055237,ALICORP S.A.A. ...,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",VICTORIA,...,4.0686,LOS OLIVOS,COBERTURA,BODEGA TIPICA,Libreta Electoral DNI,40868050,971815115,0107JUBC,-11.995142,-77.070522

In [3]:
data['Fecha'] = pd.to_datetime(data['Fecha'])
data['Dia_Semana'] = data['Fecha'].dt.day_name()

data['Rechazo'] = data['Total'] < 0

#Mostrar las siguientes columnas
data[['Fecha', 'Dia_Semana', 'Codigo_Cliente', 'Nombre_Cliente', 'Total', 'Rechazo']].head()

,Fecha,Dia_Semana,Codigo_Cliente,Nombre_Cliente,Total,Rechazo
0,2023-01-03,Tuesday,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",6.6825,False
1,2023-01-03,Tuesday,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",7.1508,False
2,2023-01-03,Tuesday,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",6.2800,False
3,2023-01-03,Tuesday,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",9.6600,False
4,2023-01-03,Tuesday,301827,"ESTELA MENDOZA, YOVANA MAGNOLIA ...",4.0686,False

In [4]:
data['Total_Compra'] = data.groupby(['Codigo_Cliente', 'Fecha'])['Total'].transform('sum')

In [5]:
columnas_a_eliminar = ['Codigo_FV', 'FV', 'Codigo_Proveedor', 'Nombre_Proveedor', 'Marca', 'Linea', 'Codigo_Producto', 'Nombre_Producto',
                       'Cantidad', 'Factor', 'ValorVenta', 'Total', 'Categoria_Cliente', 'Tipo_Cliente', 'TipoDocIdentidad', 'DocIdentidad',
                       'NumeroTelefono', 'VendedorZonaCodigo']

data = data.drop(columns=columnas_a_eliminar)

In [6]:
data = data.drop_duplicates(subset=['Codigo_Cliente', 'Fecha'])

# ConstrucciÃ³n del modelo

In [7]:
data_enconded = pd.get_dummies(data[['Dia_Semana']], drop_first=True)

data_enconded['Rechazo'] = data['Rechazo']

X = data_enconded.drop('Rechazo', axis=1)
y = data_enconded['Rechazo']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)


print("Classification Report:")
print(classification_report(y_test, y_pred))

print("confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

       False       1.00      1.00      1.00      5706
        True       0.00      0.00      0.00         9

    accuracy                           1.00      5715
   macro avg       0.50      0.50      0.50      5715
weighted avg       1.00      1.00      1.00      5715

confusion Matrix
[[5706    0]
 [   9    0]]

C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\WINDOWS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [8]:
# Crear un dataframe con los clientes Ãºnicos y sus dÃ­as sin rechazos
data_no_rechazos = data[data['Rechazo'] == False]

# Agrupar por cliente y dÃ­a de la semana para encontrar los dÃ­as sin rechazos
clientes_dias_no_rechazo = data_no_rechazos.groupby(['Codigo_Cliente', 'Nombre_Cliente'])['Dia_Semana'].apply(lambda x: list(x.unique())).reset_index()

# Renombrar las columnas
clientes_dias_no_rechazo.columns = ['Codigo_Cliente', 'Nombre_Cliente', 'Dias_Sin_Rechazo']

# Mostrar el dataframe resultante
clientes_dias_no_rechazo.head()

,Codigo_Cliente,Nombre_Cliente,Dias_Sin_Rechazo
0,219,"RAMOS ROJAS, JUANY CONZUELO ...","[Monday, Thursday]"
1,220,CHAVEZ PECHE BAUTISTA EUSEVIO ...,"[Thursday, Monday]"
2,222,BENDEZU CHAVEZ JUSTINA WILFRIDA/FARMACIA SAN F...,"[Thursday, Monday]"
3,223,URIOL VALVERDE PABLO HIPOLITO ...,"[Thursday, Monday]"
4,386,CAMPOS CASTAÃ‘EDA SONIA LUISA ...,"[Thursday, Monday]"

In [9]:
clientes_dias_no_rechazo.to_excel('clientes_dias_sin_rechazo.xlsx', index=False)

In [10]:
import pandas as pd

# Supongamos que 'data' es el dataframe original que cargamos al principio
# Y 'clientes_dias_no_rechazo' es el dataframe procesado

# Unir el dataframe original con el dataframe de dÃ­as sin rechazo
data_completo = data.merge(clientes_dias_no_rechazo, on=['Codigo_Cliente', 'Nombre_Cliente'], how='left')

# Guardar el dataframe completo a un archivo Excel
output_path_completo = 'clientes_dias_sin_rechazo_completo.xlsx'
data_completo.to_excel(output_path_completo, index=False)

print(f"Archivo exportado a {output_path_completo}")

Archivo exportado a clientes_dias_sin_rechazo_completo.xlsx